### PR TITLE
change how ArrayBlockValidator and HashBlockValidator report the field that is invalid

### PR DESCRIPTION
**Pull request by att14**
This changes the format of `field` and `message` for `Array` and `Hash` `BlockValidator`s. In particular it makes `field` contain the full path to the invalid value, e.g. `my_attr.0.my_other_attr`. This information is then stripped from the message because it is redundant.

I had to work around the fact that `:value` is not an attribute and just means validate the value with the block. I've added some `gsub`s around to remove value from certain places it was being presented.

I am relying on the current tests to ensure I didn't break anything, but if there are additional tests you would like me to add let me know.

### CODE REVIEW

**Comment by att14** [comment]
I'm going to take the silence as this is not maintained. Will be changing my forks name and creating a new Gem so I can update it.

**Comment by brycesenz** [comment]
Hey man, sorry.  I've been out of town and haven't had a chance to really update this gem in a while.  Truth be told, I don't use it much in other projects.  If you'd like, I can just make you a co-maintainer.  That will keep things I think in a better state for people who use the gem.

**Comment by att14** [comment]
No problem. Sure that sounds good to me. I'll be actively using it for a few of my upcoming projects. I'm not technically using it with ActiveRecord, just as a way to do input validation. I'll keep the tests focused on ActiveRecord because I assume that's how most people are using it.

**Comment by brycesenz** [comment]
Yeah, I actually have another library that I've since written that I find myself using more for input validation.  This was kind of a sprint library for a project I don't maintain anymore, so it doesn't get the love it deserves.  I added you as a collaborator; once you accept I can give you all the necessary permissions.

**Comment by att14** [comment]
What is the other library? And thanks.

**Comment by brycesenz** [comment]
The other library is called simple_params (https://github.com/brycesenz/simple_params).

It solves a slightly different problem, but one more in line with that I was trying to solve originally.  Let me know if you need anything else!

**Pull request closed without merging**
